spring:
  cloud:
    gateway:
      routes:
        - id : ms-customer
          uri : http://localhost:8082/
          predicates :
            - Path= /customers/**
        - id : ms-product
          uri : http://localhost:8081/
          predicates :
            - Path= /products/**
        - id: ms-biling
          uri: http://localhost:8083/
          predicates:
            - Path= /bilings/**
    discovery:
      enabled: true
